<?php defined('SYSPATH') OR die('No direct access allowed.');

/**
 * Fragment that represents anything that compiles into "... AS <alias>".
 *
 * @package    GlueDB
 * @author     Régis Lemaigre
 * @license    MIT
 */

abstract class GlueDB_Fragment_Aliased extends GlueDB_Fragment {
	/**
	 * @var string.
	 */
	protected $alias;

	/**
	 * Constructor.
	 *
	 * @param string $alias
	 */
	public function __construct($alias = null) {
		$this->alias = $alias;
	}

	/**
	 * Alias setter.
	 *
	 * @param string $alias
	 */
	public function set_alias($alias) {
		$this->alias = $alias;
		$this->invalidate();
	}

	/**
	 * Returns alias.
	 *
	 * @return string
	 */
	public function alias() {
		if ( ! isset($this->alias))
			$this->alias = $this->create_alias();
		return $this->alias;
	}

	/**
	 * Generates unique alias.
	 *
	 * @return string
	 */
	abstract protected function create_alias();

	/**
	 * Compiles the data structure against given database and returns the
	 * resulting SQL string.
	 *
	 * Null alias means : autogenerated.
	 * Empty string alias means : no ' AS ...' in SQL (i.e. no alias).
	 *
	 * @param string $dbname
	 *
	 * @return string
	 */
	protected function compile($dbname) {
		$db		= gluedb::db($dbname);
		$sqldef	= $this->compile_definition($dbname);
		if ($this->alias() === '')
			return $sqldef;
		else
			return $db->compile_alias($sqldef, $this->alias());
	}

	/**
	 * Returns SQL string for everything that must come before the "AS".
	 *
	 * @param string $dbname
	 *
	 * @return string
	 */
	abstract protected function compile_definition($dbname);
}